"""Elegoo Centauri Carbon 2 printer exception descriptions."""

EXCEPTION_NAMES: dict[int, str] = {
    101: "Bed Heat Failed",
    102: "Bed Temp Sensor Disconnected",
    103: "Nozzle Heat Failed",
    104: "Nozzle Temp Sensor Disconnected",
    105: "Nozzle Temp Sensor Shorted",
    106: "Bed Temp Sensor Shorted",
    107: "Toolhead Overheating Protection",
    108: "Bed Overheating Protection",
    109: "Filament Runout",
    205: "Chamber Temp Sensor Disconnected",
    206: "Chamber Temp Sensor Shorted",
    304: "Z Homing Failed",
    401: "Accelerometer Chip Error",
    605: "Pressure Sensor Data Error",
    701: "Mainboard Fan Error",
    702: "Heatbreak Fan Error",
    703: "Model Fan Error",
    704: "Leveling Failed",
    705: "Auxiliary Fan Error",
    706: "Case Fan Error",
    707: "Toolhead Cover Fan Detached",
    801: "Mainboard-Extruder Communication Error",
    802: "Leveling Sensor Controller Communication Error",
    803: "Critical System Error",
    901: "Chamber Temp Too High",
    902: "Chamber Temp Overheating Protection",
    903: "Mainboard Driver Unit Overheating Protection",
    904: "USB Storage Space Not Enough",
    905: "USB Read Exception",
    906: "Version Update Failed",
    1101: "Exhaust Vent Open Failed",
    1102: "Exhaust Vent Close Failed",
    1103: "Exhaust Grille Servo Close Failed",
    1104: "Y Motor Driver Error",
    1105: "Z Motor Driver Error",
    1106: "Extruder Motor Driver Error",
    1210: "Canvas Communication Error",
    1211: "Canvas Filament Runout",
    1220: "Canvas: Abnormal Filament In Extruder",
    1231: "Canvas: Cutter Knife Not Pressed",
    1232: "Canvas: Cutter Knife Not Released",
    1241: "Canvas: Feed Sensor Not Triggered",
    1242: "Canvas: Feed Self-Check Timeout",
    1243: "Canvas: Feed Blocked (Extruder)",
    1244: "Toolhead Extrusion Failed",
    1251: "Canvas: Retract Failed (Filament Broken)",
    1252: "Canvas: Retract Self-Check Timeout",
    1260: "Canvas: Filament Runout Exception",
    1261: "Toolhead Front Cover Detached",
    1262: "Canvas: Cutter Exception",
    1263: "Canvas: Filament Tangling",
    1264: "External Filament Blockage",
    1300: "Print File Unavailable",
    1301: "Spaghetti Detected",
    1302: "Print Defect Detected",
}


def exception_name(code: int) -> str:
    return EXCEPTION_NAMES.get(code, "Unknown printer error")
